#!/usr/bin/env python
"""Lyapunov spectra of the nine non-affine ECAs, at Vispoel's own settings.

Rules 6, 26, 73, 154, 41, 122, 126, 54 and 110 on a ring of N = 1000 cells with
periodic boundaries, T = 500 steps and 40 random initial configurations each,
which are the parameters of Vispoel et al. (2024), Section 6. The spectrum of
each sample is Benettin's QR estimate averaged over the last 300 steps, after a
burn-in of 200.

Three quantities are produced per sample.

* The **spectrum**: the sorted finite-time exponents of the window. This is the
  quantity the figure histograms.
* The **rank** of the tangent map over the same window, computed exactly over a
  finite field (see :func:`lyapunov.nonaffine.tangent_rank`). ``N - rank`` is the
  number of exponents that are exactly ``-inf``, which is the count Vispoel
  discards when he drops the zero eigenvalues of ``Y Y^T``. It cannot be read
  off the QR diagonal, because for rules 122, 126, 54 and 110 the near-zero
  pivots run continuously from 1e-6 down to the unit round-off.
* What **Vispoel's own method** returns at the same settings: the unscaled
  product and the eigenvalues of ``Y Y^T``. Four of the nine rules overflow
  float64 outright; for the other five the answer is confined to a band of
  width ``|ln(eps)| / (2T) = 0.036`` below the maximal exponent, because the
  precision floor sits that close to it. Both outcomes are recorded.

Seeds are fixed: sample ``s`` of rule ``r`` starts from
``default_rng([20240601, r, s])``, so the result does not depend on the order in
which the samples run and is identical at any worker count. Every worker runs
single-threaded BLAS, which also makes the QR rounding pathway reproducible.

Cost: about 92 s per sample on one core (65 s of QR, 16 s for the exact rank,
11 s for the direct method), so 360 samples are 9.2 core-hours. Ten concurrent
workers do not give a tenfold speed-up, because ten simultaneous 1000 x 1000 QR
factorisations saturate the memory bandwidth: the observed wall-clock time on a
twelve-core laptop was about three and a half hours.

Outputs (regenerated by the figure script if missing):
    data/nonaffine/spectra.npz              the raw per-sample results
    data/tables/nonaffine_spectra.csv       one row per rule (the summary)
    data/tables/nonaffine_direct_multiplication.csv   what Vispoel's method does

Usage:
    python data/make_nonaffine_spectra.py --recompute            # the full run
    python data/make_nonaffine_spectra.py --recompute --N 200 --samples 4
"""
from __future__ import annotations

import argparse
import csv
import os
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

for _var in ("OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ.setdefault(_var, "1")     # before numpy: single-thread QR, identical numbers

import numpy as np

from lyapunov.benettin import precision_floor
from lyapunov.jacobian import eca_jacobian
from lyapunov.rules import affine_ecas, nonequivalent_ecas
from lyapunov.nonaffine import (
    direct_multiplication_trajectory,
    integer_matrix_rank,
    spectrum_along_trajectory,
    tangent_rank,
)
from lyapunov.spectra import eca_singular_values

# Vispoel et al. (2024), Section 6, plus the burn-in this package adds.
RULES = (6, 26, 73, 154, 41, 122, 126, 54, 110)
N_DEFAULT = 1000
T_DEFAULT = 500
BURN_DEFAULT = 200
SAMPLES_DEFAULT = 40
SEED = 20240601                  # the repository's canonical seed

# Three affine rules for comparison. Their Jacobian is constant, so the spectrum
# is the closed form of lyapunov.spectra: no trajectory, no sampling, no
# burn-in. Rules 60 and 90 are the gradient-weight-2 pair and 150 the
# weight-3 maximum.
AFFINE_RULES = (60, 90, 150)

# The --all-88 catalogue: every ECA up to reflection and conjugation, split by
# whether it needs a trajectory. Nine of the 88 are affine and come from the
# closed form in milliseconds; the other 79 are the expensive ones.
ALL_88_AFFINE = tuple(sorted(set(nonequivalent_ecas()) & set(affine_ecas())))
ALL_88_RULES = tuple(r for r in nonequivalent_ecas() if r not in ALL_88_AFFINE)

DATA_DIR = Path(__file__).resolve().parent
CACHE = DATA_DIR / "nonaffine" / "spectra.npz"
CACHE_88 = DATA_DIR / "nonaffine" / "spectra_all88.npz"
TABLE_DIR = DATA_DIR / "tables"


def initial_state(rule: int, sample: int, N: int, seed: int = SEED) -> np.ndarray:
    """The seeded random initial configuration of one sample."""
    return np.random.default_rng([seed, rule, sample]).integers(0, 2, size=N)


def affine_results(rules=AFFINE_RULES, N: int = N_DEFAULT) -> dict:
    """Exact spectra of the affine rules, and their exact count of zero exponents.

    ``eca_singular_values`` returns the closed form, in which a singular value
    that is algebraically zero comes back as a rounding-level number instead, so
    its logarithm is a meaningless -36 rather than ``-inf``. The count of true
    zeros is therefore taken as ``N - rank(J)`` with the rank computed exactly
    over a finite field, exactly as for the non-affine rules. ``J`` is normal
    here, so the rank of its powers equals the rank of ``J`` and one matrix
    suffices.
    """
    spectra = np.empty((len(rules), N))
    ranks = np.empty(len(rules), dtype=np.int64)
    for i, rule in enumerate(rules):
        with np.errstate(divide="ignore"):
            spectra[i] = np.sort(np.log(eca_singular_values(rule, N)))[::-1]
        ranks[i] = integer_matrix_rank(eca_jacobian(rule, N))
    return {"affine_rules": np.array(rules), "affine_spectra": spectra,
            "affine_ranks": ranks}


def run_sample(task: tuple) -> dict:
    """One rule, one initial configuration: spectrum, exact rank, direct method."""
    rule, sample, N, T, burn, seed, with_direct = task
    state = initial_state(rule, sample, N, seed)
    result = {
        "rule": rule,
        "sample": sample,
        "spectrum": spectrum_along_trajectory(rule, state, T, burn),
        "rank": tangent_rank(rule, state, burn, T - burn),
    }
    if not with_direct:
        return result
    # Vispoel's route, on the same trajectory and the same horizon.
    try:
        result["direct"] = direct_multiplication_trajectory(rule, state, T)
        result["direct_overflow"] = False
    except OverflowError:
        result["direct"] = np.full(N, np.nan)
        result["direct_overflow"] = True
    return result


def partial_path(cache: Path) -> Path:
    """Where a run in progress stores what it has finished."""
    return cache.with_name(cache.stem + ".partial.npz")


def compute(rules, N, T, burn, samples, seed, workers, with_direct=True,
            partial: Path | None = None, resume: bool = False,
            checkpoint_every: int = 100) -> dict:
    """Run every (rule, sample) pair in a pool of single-threaded workers.

    A run over all 88 rules takes hours, so the accumulated arrays are written
    to ``partial`` every ``checkpoint_every`` samples, together with a mask of
    what is finished. ``resume`` picks that up and submits only the samples
    that are missing; since each sample is seeded from ``(seed, rule, sample)``
    alone, a resumed run gives bitwise the same answer as an uninterrupted one.
    """
    index = {rule: i for i, rule in enumerate(rules)}
    out = {
        "rules": np.array(rules),
        "spectra": np.empty((len(rules), samples, N)),
        "ranks": np.empty((len(rules), samples), dtype=np.int64),
    }
    if with_direct:
        # float32 is ample for a quantity whose whole point is that it carries
        # no information below the precision floor, and halves the cache.
        out.update(direct=np.full((len(rules), samples, N), np.nan, dtype=np.float32),
                   direct_overflow=np.zeros((len(rules), samples), dtype=bool))
    finished = np.zeros((len(rules), samples), dtype=bool)

    if resume and partial is not None and partial.exists():
        with np.load(partial) as prev:
            same = (list(prev["rules"]) == list(rules)
                    and prev["spectra"].shape == out["spectra"].shape
                    and (int(prev["N"]), int(prev["T"]), int(prev["burn"]),
                         int(prev["seed"])) == (N, T, burn, seed))
            if same:
                out["spectra"][:] = prev["spectra"]
                out["ranks"][:] = prev["ranks"]
                finished = prev["finished"]
                if with_direct and "direct" in prev.files:
                    out["direct"][:] = prev["direct"]
                    out["direct_overflow"][:] = prev["direct_overflow"]
                print(f"resuming {partial}: {int(finished.sum())} of "
                      f"{finished.size} samples are already done")
            else:
                print(f"{partial} is from a different run; ignoring it")

    tasks = [(rule, s, N, T, burn, seed, with_direct)
             for i, rule in enumerate(rules) for s in range(samples)
             if not finished[i, s]]
    if not tasks:
        print("every sample is already in the checkpoint")

    def save_partial():
        if partial is None:
            return
        partial.parent.mkdir(parents=True, exist_ok=True)
        np.savez(partial, finished=finished, N=N, T=T, burn=burn,
                 samples=samples, seed=seed, **out)

    start = time.time()
    done = 0
    with ProcessPoolExecutor(max_workers=workers) as pool:
        futures = [pool.submit(run_sample, task) for task in tasks]
        for future in as_completed(futures):
            r = future.result()
            i, j = index[r["rule"]], r["sample"]
            out["spectra"][i, j] = r["spectrum"]
            out["ranks"][i, j] = r["rank"]
            if with_direct:
                out["direct"][i, j] = r["direct"]
                out["direct_overflow"][i, j] = r["direct_overflow"]
            finished[i, j] = True
            done += 1
            if done % checkpoint_every == 0:
                save_partial()
            elapsed = time.time() - start
            print(f"\r  {done}/{len(tasks)} samples, {elapsed / 60:.1f} min elapsed, "
                  f"{elapsed / done * (len(tasks) - done) / 60:.1f} min left   ",
                  end="", flush=True)
    print()
    save_partial()
    for key, value in (("N", N), ("T", T), ("burn", burn),
                       ("samples", samples), ("seed", seed)):
        out[key] = np.array(value)
    return out


def summary_rows(data: dict) -> list[dict]:
    """One row per rule: the spectrum, the MLE and the share of -inf exponents."""
    N, window = int(data["N"]), int(data["T"]) - int(data["burn"])
    rows = []
    for i, rule in enumerate(data["rules"]):
        method = f"Benettin ({int(data['samples'])} samples)"
        spectra, ranks = data["spectra"][i], data["ranks"][i]
        mle = spectra[:, 0]
        # The smallest exponent that is not -inf; a rank of zero would mean the
        # tangent map annihilates everything, which none of these rules does.
        kept_min = np.array([s[r - 1] if r > 0 else np.nan for s, r in zip(spectra, ranks)])
        minus_inf = 100.0 * (N - ranks) / N
        rows.append({
            "rule": int(rule),
            "affine": False,
            "method": method,
            "N": N,
            "T": int(data["T"]),
            "burn": int(data["burn"]),
            "window": window,
            "samples": int(data["samples"]),
            "mle_mean": f"{mle.mean():.6f}",
            "mle_sd": f"{mle.std(ddof=1):.6f}" if mle.size > 1 else "",
            # The 16th and 84th percentiles of the 40 sample maxima: the
            # asymmetric spread Figure 6 annotates. Rule 73's is markedly
            # one-sided, which a standard deviation alone would hide.
            "mle_p16": f"{np.percentile(mle, 16):.6f}",
            "mle_p84": f"{np.percentile(mle, 84):.6f}",
            "finite_exponents_mean": f"{ranks.mean():.1f}",
            "pct_minus_inf_mean": f"{minus_inf.mean():.2f}",
            "pct_minus_inf_min": f"{minus_inf.min():.2f}",
            "pct_minus_inf_max": f"{minus_inf.max():.2f}",
            "lambda_min_finite_mean": f"{kept_min.mean():.6f}",
        })
    for i, rule in enumerate(data.get("affine_rules", [])):
        spectrum, rank = data["affine_spectra"][i], int(data["affine_ranks"][i])
        share = 100.0 * (N - rank) / N
        rows.append({
            "rule": int(rule),
            "affine": True,
            "method": "closed form",
            "N": N, "T": "", "burn": "", "window": "", "samples": 1,
            "mle_mean": f"{spectrum[0]:.6f}",
            "mle_sd": "",
            "mle_p16": "",             # exact: no sampling spread
            "mle_p84": "",
            "finite_exponents_mean": f"{rank:.1f}",
            "pct_minus_inf_mean": f"{share:.2f}",
            "pct_minus_inf_min": f"{share:.2f}",
            "pct_minus_inf_max": f"{share:.2f}",
            # Rule 0 is in the --all-88 set and annihilates everything: its
            # rank is zero, so there is no finite exponent to report.
            "lambda_min_finite_mean": (f"{spectrum[rank - 1]:.6f}" if rank else ""),
        })
    return rows


def direct_rows(data: dict) -> list[dict]:
    """One row per rule: what the unscaled direct method returns at these settings."""
    N, T = int(data["N"]), int(data["T"])
    rows = []
    for i, rule in enumerate(data["rules"]):
        mle = float(data["spectra"][i][:, 0].mean())
        sigma_max = float(np.exp(mle))
        floor = precision_floor(sigma_max, T)
        spectra, ranks = data["spectra"][i], data["ranks"][i]
        true_above = np.mean([(s[:k] >= floor).sum() for s, k in zip(spectra, ranks)])
        overflow = data["direct_overflow"][i]
        values = data["direct"][i][~overflow].astype(np.float64)
        finite = [v[np.isfinite(v)] for v in values]
        lo = np.array([v.min() for v in finite if v.size])
        hi = np.array([v.max() for v in finite if v.size])
        # The only exponents the method resolves are those above its own floor;
        # everything below is rounding noise, which scatters rather than piling
        # up exactly at the floor.
        above = np.array([int((v >= floor).sum()) for v in finite])
        n_nan = np.array([int(np.isnan(v).sum()) for v in values])
        rows.append({
            "rule": int(rule),
            "mle": f"{mle:.6f}",
            "sigma_max": f"{sigma_max:.6f}",
            "precision_floor": f"{floor:.6f}",
            "resolvable_band_width": f"{mle - floor:.6f}",
            "log10_largest_eigenvalue": f"{2 * T * mle / np.log(10):.1f}",
            "samples": int(overflow.size),
            "samples_overflowed": int(overflow.sum()),
            "true_exponents_above_floor_mean": f"{true_above:.1f}",
            "reported_min": f"{lo.mean():.6f}" if lo.size else "",
            "reported_max": f"{hi.mean():.6f}" if hi.size else "",
            "exponents_above_floor_mean": f"{above.mean():.1f}" if above.size else "0",
            "exponents_inside_the_band_mean": (
                f"{np.mean([((v >= floor) & (v <= mle)).sum() for v in values]):.1f}"
                if values.size else "0"),
            "exponents_returned_as_nan_mean": f"{n_nan.mean():.1f}" if n_nan.size else f"{N}",
            "outcome": ("overflows float64" if overflow.all() else
                        f"{above.mean():.0f} exponents reported above a floor only "
                        f"{true_above:.0f} of them reach"
                        if not overflow.any() else "overflows on some samples"),
        })
    return rows


def _write_csv(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def load(cache: Path = CACHE) -> dict:
    """Read the cached run back as a plain dictionary of arrays."""
    with np.load(cache) as handle:
        return {key: handle[key] for key in handle.files}


def matches(data: dict, N: int, T: int, burn: int, samples: int, rules) -> bool:
    """True if a cached run was made with exactly these parameters."""
    return (int(data["N"]) == N and int(data["T"]) == T and int(data["burn"]) == burn
            and int(data["samples"]) == samples
            and list(data["rules"]) == list(rules))


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--N", type=int, default=N_DEFAULT)
    p.add_argument("--T", type=int, default=T_DEFAULT)
    p.add_argument("--burn", type=int, default=BURN_DEFAULT)
    p.add_argument("--samples", type=int, default=SAMPLES_DEFAULT)
    p.add_argument("--seed", type=int, default=SEED)
    p.add_argument("--workers", type=int, default=max(1, (os.cpu_count() or 2) - 2),
                   help="single-threaded workers; more is not always faster, "
                        "because concurrent QR factorisations saturate the "
                        "memory bandwidth (see data/bench_workers.py)")
    p.add_argument("--cache", default=None)
    p.add_argument("--all-88", dest="all_88", action="store_true",
                   help="every ECA up to reflection and conjugation: 79 by "
                        "trajectory and 9 affine ones from the closed form, "
                        "into data/nonaffine/spectra_all88.npz")
    p.add_argument("--resume", action="store_true",
                   help="continue from the .partial.npz checkpoint of an "
                        "interrupted run")
    p.add_argument("--recompute", action="store_true",
                   help="run even if a matching cache is present")
    p.add_argument("--tables-only", action="store_true",
                   help="rewrite the CSV tables from the cache, without computing")
    p.add_argument("--affine-only", action="store_true",
                   help="refresh only the closed-form affine spectra in the cache")
    p.add_argument("--skip-direct", action="store_true",
                   help="skip Vispoel's method (the failure table is then not written)")
    args = p.parse_args(argv)
    rules = ALL_88_RULES if args.all_88 else RULES
    affine = ALL_88_AFFINE if args.all_88 else AFFINE_RULES
    stem = "all88" if args.all_88 else "nonaffine"
    cache = Path(args.cache) if args.cache else (CACHE_88 if args.all_88 else CACHE)
    # A run at other parameters is a calibration, not the manuscript's numbers:
    # keep its tables beside its own cache rather than in data/tables.
    default_run = (args.N, args.T, args.burn, args.samples, args.seed) == (
        N_DEFAULT, T_DEFAULT, BURN_DEFAULT, SAMPLES_DEFAULT, SEED)
    table_dir = TABLE_DIR if default_run and cache == CACHE else cache.parent

    # Both of these work from the stored run and must never start a computation.
    reuse_cache = args.affine_only or args.tables_only
    if args.affine_only:
        data = load(cache)
        data.update(affine_results(affine, int(data["N"])))
        np.savez_compressed(cache, **data)
        print(f"refreshed the affine spectra in {cache}")
    elif args.tables_only:
        data = load(cache)
        print(f"rewriting the tables from {cache}")
    elif cache.exists() and not args.recompute:
        data = load(cache)
        if matches(data, args.N, args.T, args.burn, args.samples, rules):
            print(f"{cache} already holds this run; pass --recompute to redo it.")
            return 0
        print(f"{cache} was made with different parameters; recomputing.")

    if not reuse_cache:
        print(f"{len(rules)} rules x {args.samples} samples, N = {args.N}, "
              f"T = {args.T}, burn-in {args.burn}, on {args.workers} "
              "single-threaded workers")
        partial = partial_path(cache)
        data = compute(rules, args.N, args.T, args.burn, args.samples, args.seed,
                       args.workers, with_direct=not args.skip_direct,
                       partial=partial, resume=args.resume)
        data.update(affine_results(affine, args.N))
        cache.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(cache, **data)
        print(f"Wrote {cache} ({cache.stat().st_size / 1e6:.1f} MB)")
        partial.unlink(missing_ok=True)      # the run completed; drop the checkpoint

    rows = summary_rows(data)
    summary_csv = table_dir / f"{stem}_spectra.csv"
    _write_csv(rows, summary_csv)
    print(f"Wrote {len(rows)} rows to {summary_csv}")
    for row in rows:
        print(f"  rule {row['rule']:4d}: MLE {row['mle_mean']} +/- {row['mle_sd']}, "
              f"{row['pct_minus_inf_mean']} % of the spectrum is -inf")

    if "direct" in data:
        rows = direct_rows(data)
        direct_csv = table_dir / f"{stem}_direct_multiplication.csv"
        _write_csv(rows, direct_csv)
        print(f"Wrote {len(rows)} rows to {direct_csv}")
        for row in rows:
            print(f"  rule {row['rule']:4d}: floor {row['precision_floor']}, band "
                  f"{row['resolvable_band_width']} wide, {row['outcome']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
